version: 2

models:
  - name: staging_products
    description: clean version of products table
    columns:
      - name: products_id
        description: id of the products
        tests:
          - not_null
      - name: purchase_price
        description: price of the product
  - name: staging_shipment
    description: clean version of shipment table
    columns:
      - name: orders_id
        description: id of the orders
        tests:
          - not_null
          - unique
      - name: shipping_fee
        description: the money paid for the shipment --by customer, i guess
        tests:
          - not_null
      - name: log_cost
        description: logistics cost paid by the seller
        tests:
          - not_null
      - name: ship_cost
        description: shipment cost paid by the seller
        tests:
          - not_null
  - name: staging_adwords
    columns:
      - name: date_date
        description: dates of the campaigns
        tests:
          - not_null
      - name: pk_key
        description: primary key
        tests:
          - unique
          - not_null
  - name: staging_bing
    columns:
      - name: date_date
        description: dates of the campaigns
        tests:
          - not_null
      - name: pk_key
        description: primary key
        tests:
          - unique
          - not_null