version: 2

models:
  - name: int__cc_parcel_product
    columns:
      - name: parcel_id
        tests:
          - not_null
          - unique
      - name: status
        tests:
          - not_null