version: 2

sources:
  - name: raw
    decription: raw data dataset
    schema: gz_raw_data
    tables:
      - name: sales
        description: sales table
        identifier: gz_raw_sales
        columns:
          - name: date_date
            description: date of the sales
          - name: orders_id
            description: primary key probably
          - name: pdt_id
          - name: revenue
          - name: quantity