version: 2

models:
  - name: stg__cc_parcel_product
    description: parcel product table cleaned version
    columns:
      - name: parcel_id
      - name: model_name
      - name: quantity
  - name: stg__cc_parcel
    description: parcel table 
    columns:
      - name: parcel_id
        tests:
          - unique
