version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables: 
      - name: sales
        identifier: raw_gz_sales
        description: raw sales data table includes raw sales data
        columns: 
          - name: date_date
            description: date of the sale
            tests:
              - not_null
          - name: orders_id
            description: id of the order
            tests:
              - not_null
          - name: pdt_id
            description: products' id of the sales
            tests:
              - not_null
        tests:
          - unique:
            column name: 'date_date || orders_id || pdt_id'
      - name: products
        identifier: raw_gz_product
        description: raw products data of greenwez
        columns: 
          - name: products_id
            description: id numbers of the products
            tests: 
              - not_null
          - name: purchSE_PRICE
            description: buying prices of the products
            tests:
              - not_null
        tests: 
          - unique:
              column_name: 'products_id'
      - name: shipment
        identifier: raw_gz_ship
        description: shipment data of greeenwez
        columns:
          - name: orders_id
            description: id numbers of orders
            tests:
              - not_null
          - name: shipping_fee
            description: the money that customers pay for the shipment
            tests:
              - not_null
          - name: ship_cost
            description: the money sellers pay for the shipment
            tests:
              - not_null
        tests:
          - unique:
              column_name: orders_id
            

            
                  