version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables: 
      - name: sales
        identifier: raw_gz_sales
        description: raw sales data table includes raw sales data
        columns: 
          - name: date_date
            description: date of the sale
            tests:
              - not_null
          - name: orders_id
            description: id of the order
            tests:
              - not_null
          - name: pdt_id
            description: products' id of the sales
            tests:
              - not_null
      - name: products
        identifier: raw_gz_product
        description: raw products data of greenwez
        columns: 
          - name: products_id
            description: id numbers of the products
            tests: 
              - not_null
          - name: purchSE_PRICE
            description: buying prices of the products
            tests:
              - not_null
        tests: 
          - unique:
              column_name: 'products_id'
      - name: shipment
        identifier: raw_gz_ship
        description: shipment data of greeenwez
        columns:
          - name: orders_id
            description: id numbers of orders
            tests:
              - not_null
          - name: shipping_fee
            description: the money that customers pay for the shipment
            tests:
              - not_null
          - name: ship_cost
            description: the money sellers pay for the shipment
            tests:
              - not_null
        tests:
          - unique:
              column_name: orders_id
      - name: gz_adwords 
        identifier: raw_gz_adwords
        description: adwords campaing dataset
        columns: 
          - name: date_date
            description: date of the campaigns
          - name: paid_source
            description: the social media platform where the ad is shared
          - name: campaign_key
            description: primary key of this table
            tests:
              - not_null
          - name: ads_cost
            description: the amount of money used for one of the ads
      - name: gz_bing 
        identifier: raw_gz_bing
        description: raw bing campaigns
        columns:
          - name: campaign_key
            description: probably primary key
            tests:
              - not_null
      - name: gz_criteo
        identifier: raw_gz_criteo
        description: criteo ads raw dataset
        columns:
          - name: campaign_key
            description: probably primary key
            tests:
              - not_null
      - name: gz_facebook
        description: facebook campaigns dataset raw
        identifier: raw_gz_facebook
        columns:
          - name: campaign_key
            description: probably primary key 
            tests:
              - not_null




            
                  